# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hep Oils
email: bradleybirch09@yahoo.co.uk
description: > #
  Hep Oils take care of all your requirements with regard to supply & collection
  of cooking oils. We will ensure all waste is recycled, allowing you to continue your daily business
  safe in the knowledge that you are not only compliant but able to show due consideration to the constant
  need to recycle, renew & replenish.

#baseurl: "" # the subpath of your site, e.g. /blog. Use this for DEV
#url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com

baseurl: "" #use this for PROD
url: "http://hepoils.com/" # use this for PROD

#baseurl: "/silverbirchh.github.io-hepoils/" #use this for TEST
#url: "https://silverbirchh.github.io" # use this for TEST

permalink: none

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
include: ['_pages', 'images', 'js']
gems:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock

plugins_dir:
  - jekyll-seo-tag
